// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: SormIpNumbering)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSormIpNumbering is a mock of SormIpNumbering interface.
type MockSormIpNumbering struct {
	ctrl     *gomock.Controller
	recorder *MockSormIpNumberingMockRecorder
}

// MockSormIpNumberingMockRecorder is the mock recorder for MockSormIpNumbering.
type MockSormIpNumberingMockRecorder struct {
	mock *MockSormIpNumbering
}

// NewMockSormIpNumbering creates a new mock instance.
func NewMockSormIpNumbering(ctrl *gomock.Controller) *MockSormIpNumbering {
	mock := &MockSormIpNumbering{ctrl: ctrl}
	mock.recorder = &MockSormIpNumberingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSormIpNumbering) EXPECT() *MockSormIpNumberingMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSormIpNumbering) Create(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSormIpNumberingMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSormIpNumbering)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSormIpNumbering) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSormIpNumberingMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSormIpNumbering)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSormIpNumbering) Get() ([]models.SormIpNumberingData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormIpNumberingData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSormIpNumberingMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSormIpNumbering)(nil).Get))
}

// Update mocks base method.
func (m *MockSormIpNumbering) Update(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSormIpNumberingMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSormIpNumbering)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockSormIpNumbering) Upsert(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSormIpNumberingMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSormIpNumbering)(nil).Upsert), arg0)
}
