// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DeviceInterfaces)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceInterfaces is a mock of DeviceInterfaces interface.
type MockDeviceInterfaces struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceInterfacesMockRecorder
}

// MockDeviceInterfacesMockRecorder is the mock recorder for MockDeviceInterfaces.
type MockDeviceInterfacesMockRecorder struct {
	mock *MockDeviceInterfaces
}

// NewMockDeviceInterfaces creates a new mock instance.
func NewMockDeviceInterfaces(ctrl *gomock.Controller) *MockDeviceInterfaces {
	mock := &MockDeviceInterfaces{ctrl: ctrl}
	mock.recorder = &MockDeviceInterfacesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceInterfaces) EXPECT() *MockDeviceInterfacesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceInterfaces) Create(arg0 models.IfaceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceInterfacesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceInterfaces)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDeviceInterfaces) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceInterfacesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceInterfaces)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockDeviceInterfaces) Get() ([]models.IfaceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.IfaceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceInterfacesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceInterfaces)(nil).Get))
}

// GetByDeviceIdAndPort mocks base method.
func (m *MockDeviceInterfaces) GetByDeviceIdAndPort(arg0 string, arg1 int) (models.IfaceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDeviceIdAndPort", arg0, arg1)
	ret0, _ := ret[0].(models.IfaceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDeviceIdAndPort indicates an expected call of GetByDeviceIdAndPort.
func (mr *MockDeviceInterfacesMockRecorder) GetByDeviceIdAndPort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDeviceIdAndPort", reflect.TypeOf((*MockDeviceInterfaces)(nil).GetByDeviceIdAndPort), arg0, arg1)
}

// Update mocks base method.
func (m *MockDeviceInterfaces) Update(arg0 models.IfaceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceInterfacesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceInterfaces)(nil).Update), arg0)
}
