// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: IssueActions)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIssueActions is a mock of IssueActions interface.
type MockIssueActions struct {
	ctrl     *gomock.Controller
	recorder *MockIssueActionsMockRecorder
}

// MockIssueActionsMockRecorder is the mock recorder for MockIssueActions.
type MockIssueActionsMockRecorder struct {
	mock *MockIssueActions
}

// NewMockIssueActions creates a new mock instance.
func NewMockIssueActions(ctrl *gomock.Controller) *MockIssueActions {
	mock := &MockIssueActions{ctrl: ctrl}
	mock.recorder = &MockIssueActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueActions) EXPECT() *MockIssueActionsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIssueActions) Create(arg0 models.IssueActionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIssueActionsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueActions)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIssueActions) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueActionsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueActions)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockIssueActions) Get() ([]models.IssueActionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.IssueActionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueActionsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueActions)(nil).Get))
}

// Update mocks base method.
func (m *MockIssueActions) Update(arg0 models.IssueActionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIssueActionsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueActions)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockIssueActions) Upsert(arg0 models.IssueActionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIssueActionsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIssueActions)(nil).Upsert), arg0)
}
