// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DeviceInterfaceStates)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceInterfaceStates is a mock of DeviceInterfaceStates interface.
type MockDeviceInterfaceStates struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceInterfaceStatesMockRecorder
}

// MockDeviceInterfaceStatesMockRecorder is the mock recorder for MockDeviceInterfaceStates.
type MockDeviceInterfaceStatesMockRecorder struct {
	mock *MockDeviceInterfaceStates
}

// NewMockDeviceInterfaceStates creates a new mock instance.
func NewMockDeviceInterfaceStates(ctrl *gomock.Controller) *MockDeviceInterfaceStates {
	mock := &MockDeviceInterfaceStates{ctrl: ctrl}
	mock.recorder = &MockDeviceInterfaceStatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceInterfaceStates) EXPECT() *MockDeviceInterfaceStatesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceInterfaceStates) Create(arg0 models.IfaceStateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceInterfaceStatesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceInterfaceStates)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDeviceInterfaceStates) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceInterfaceStatesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceInterfaceStates)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockDeviceInterfaceStates) Get() ([]models.IfaceStateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.IfaceStateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceInterfaceStatesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceInterfaceStates)(nil).Get))
}

// Update mocks base method.
func (m *MockDeviceInterfaceStates) Update(arg0 models.IfaceStateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceInterfaceStatesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceInterfaceStates)(nil).Update), arg0)
}
