// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: IssueUrgencies)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIssueUrgencies is a mock of IssueUrgencies interface.
type MockIssueUrgencies struct {
	ctrl     *gomock.Controller
	recorder *MockIssueUrgenciesMockRecorder
}

// MockIssueUrgenciesMockRecorder is the mock recorder for MockIssueUrgencies.
type MockIssueUrgenciesMockRecorder struct {
	mock *MockIssueUrgencies
}

// NewMockIssueUrgencies creates a new mock instance.
func NewMockIssueUrgencies(ctrl *gomock.Controller) *MockIssueUrgencies {
	mock := &MockIssueUrgencies{ctrl: ctrl}
	mock.recorder = &MockIssueUrgenciesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueUrgencies) EXPECT() *MockIssueUrgenciesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIssueUrgencies) Create(arg0 models.IssueUrgencyData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIssueUrgenciesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueUrgencies)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIssueUrgencies) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueUrgenciesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueUrgencies)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockIssueUrgencies) Get() ([]models.IssueUrgencyData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.IssueUrgencyData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueUrgenciesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueUrgencies)(nil).Get))
}

// Update mocks base method.
func (m *MockIssueUrgencies) Update(arg0 models.IssueUrgencyData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIssueUrgenciesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueUrgencies)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockIssueUrgencies) Upsert(arg0 models.IssueUrgencyData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIssueUrgenciesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIssueUrgencies)(nil).Upsert), arg0)
}
