// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DhcpBindings)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDhcpBindings is a mock of DhcpBindings interface.
type MockDhcpBindings struct {
	ctrl     *gomock.Controller
	recorder *MockDhcpBindingsMockRecorder
}

// MockDhcpBindingsMockRecorder is the mock recorder for MockDhcpBindings.
type MockDhcpBindingsMockRecorder struct {
	mock *MockDhcpBindings
}

// NewMockDhcpBindings creates a new mock instance.
func NewMockDhcpBindings(ctrl *gomock.Controller) *MockDhcpBindings {
	mock := &MockDhcpBindings{ctrl: ctrl}
	mock.recorder = &MockDhcpBindingsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDhcpBindings) EXPECT() *MockDhcpBindingsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDhcpBindings) Create(arg0 []models.DhcpBindingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDhcpBindingsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDhcpBindings)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDhcpBindings) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDhcpBindingsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDhcpBindings)(nil).Delete), arg0)
}

// DeleteAll mocks base method.
func (m *MockDhcpBindings) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockDhcpBindingsMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockDhcpBindings)(nil).DeleteAll))
}

// Get mocks base method.
func (m *MockDhcpBindings) Get() ([]models.DhcpBindingData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.DhcpBindingData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDhcpBindingsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDhcpBindings)(nil).Get))
}

// Update mocks base method.
func (m *MockDhcpBindings) Update(arg0 models.DhcpBindingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDhcpBindingsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDhcpBindings)(nil).Update), arg0)
}
