// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DocumentTypes)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDocumentTypes is a mock of DocumentTypes interface.
type MockDocumentTypes struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentTypesMockRecorder
}

// MockDocumentTypesMockRecorder is the mock recorder for MockDocumentTypes.
type MockDocumentTypesMockRecorder struct {
	mock *MockDocumentTypes
}

// NewMockDocumentTypes creates a new mock instance.
func NewMockDocumentTypes(ctrl *gomock.Controller) *MockDocumentTypes {
	mock := &MockDocumentTypes{ctrl: ctrl}
	mock.recorder = &MockDocumentTypesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentTypes) EXPECT() *MockDocumentTypesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentTypes) Create(arg0 models.DocumentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDocumentTypesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentTypes)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDocumentTypes) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentTypesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentTypes)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockDocumentTypes) Get() ([]models.DocumentTypeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.DocumentTypeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDocumentTypesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDocumentTypes)(nil).Get))
}

// Update mocks base method.
func (m *MockDocumentTypes) Update(arg0 models.DocumentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDocumentTypesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDocumentTypes)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockDocumentTypes) Upsert(arg0 models.DocumentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDocumentTypesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDocumentTypes)(nil).Upsert), arg0)
}
