// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: SormCustomersErrors)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSormCustomersErrors is a mock of SormCustomersErrors interface.
type MockSormCustomersErrors struct {
	ctrl     *gomock.Controller
	recorder *MockSormCustomersErrorsMockRecorder
}

// MockSormCustomersErrorsMockRecorder is the mock recorder for MockSormCustomersErrors.
type MockSormCustomersErrorsMockRecorder struct {
	mock *MockSormCustomersErrors
}

// NewMockSormCustomersErrors creates a new mock instance.
func NewMockSormCustomersErrors(ctrl *gomock.Controller) *MockSormCustomersErrors {
	mock := &MockSormCustomersErrors{ctrl: ctrl}
	mock.recorder = &MockSormCustomersErrorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSormCustomersErrors) EXPECT() *MockSormCustomersErrorsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSormCustomersErrors) Create(arg0 []models.SormCustomersErrorsData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSormCustomersErrorsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSormCustomersErrors)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSormCustomersErrors) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSormCustomersErrorsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSormCustomersErrors)(nil).Delete), arg0)
}

// DeleteAll mocks base method.
func (m *MockSormCustomersErrors) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockSormCustomersErrorsMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockSormCustomersErrors)(nil).DeleteAll))
}

// Get mocks base method.
func (m *MockSormCustomersErrors) Get() ([]models.SormCustomersErrorsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormCustomersErrorsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSormCustomersErrorsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSormCustomersErrors)(nil).Get))
}

// Update mocks base method.
func (m *MockSormCustomersErrors) Update(arg0 models.SormCustomersErrorsData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSormCustomersErrorsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSormCustomersErrors)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockSormCustomersErrors) Upsert(arg0 []models.SormCustomersErrorsData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSormCustomersErrorsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSormCustomersErrors)(nil).Upsert), arg0)
}
