// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: SormCustomerServices)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSormCustomerServices is a mock of SormCustomerServices interface.
type MockSormCustomerServices struct {
	ctrl     *gomock.Controller
	recorder *MockSormCustomerServicesMockRecorder
}

// MockSormCustomerServicesMockRecorder is the mock recorder for MockSormCustomerServices.
type MockSormCustomerServicesMockRecorder struct {
	mock *MockSormCustomerServices
}

// NewMockSormCustomerServices creates a new mock instance.
func NewMockSormCustomerServices(ctrl *gomock.Controller) *MockSormCustomerServices {
	mock := &MockSormCustomerServices{ctrl: ctrl}
	mock.recorder = &MockSormCustomerServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSormCustomerServices) EXPECT() *MockSormCustomerServicesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSormCustomerServices) Create(arg0 []models.SormCustomerServiceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSormCustomerServicesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSormCustomerServices)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSormCustomerServices) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSormCustomerServicesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSormCustomerServices)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSormCustomerServices) Get() ([]models.SormCustomerServiceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormCustomerServiceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSormCustomerServicesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSormCustomerServices)(nil).Get))
}

// Update mocks base method.
func (m *MockSormCustomerServices) Update(arg0 models.SormCustomerServiceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSormCustomerServicesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSormCustomerServices)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockSormCustomerServices) Upsert(arg0 []models.SormCustomerServiceData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSormCustomerServicesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSormCustomerServices)(nil).Upsert), arg0)
}
