// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: PaymentTypes)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentTypes is a mock of PaymentTypes interface.
type MockPaymentTypes struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentTypesMockRecorder
}

// MockPaymentTypesMockRecorder is the mock recorder for MockPaymentTypes.
type MockPaymentTypesMockRecorder struct {
	mock *MockPaymentTypes
}

// NewMockPaymentTypes creates a new mock instance.
func NewMockPaymentTypes(ctrl *gomock.Controller) *MockPaymentTypes {
	mock := &MockPaymentTypes{ctrl: ctrl}
	mock.recorder = &MockPaymentTypesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentTypes) EXPECT() *MockPaymentTypesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentTypes) Create(arg0 models.PaymentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentTypesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentTypes)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockPaymentTypes) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentTypesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentTypes)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockPaymentTypes) Get() ([]models.PaymentTypeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.PaymentTypeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentTypesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentTypes)(nil).Get))
}

// Update mocks base method.
func (m *MockPaymentTypes) Update(arg0 models.PaymentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentTypesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentTypes)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockPaymentTypes) Upsert(arg0 models.PaymentTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPaymentTypesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPaymentTypes)(nil).Upsert), arg0)
}
