// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: SormCustomers)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSormCustomers is a mock of SormCustomers interface.
type MockSormCustomers struct {
	ctrl     *gomock.Controller
	recorder *MockSormCustomersMockRecorder
}

// MockSormCustomersMockRecorder is the mock recorder for MockSormCustomers.
type MockSormCustomersMockRecorder struct {
	mock *MockSormCustomers
}

// NewMockSormCustomers creates a new mock instance.
func NewMockSormCustomers(ctrl *gomock.Controller) *MockSormCustomers {
	mock := &MockSormCustomers{ctrl: ctrl}
	mock.recorder = &MockSormCustomersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSormCustomers) EXPECT() *MockSormCustomersMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSormCustomers) Create(arg0 []models.SormCustomersData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSormCustomersMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSormCustomers)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSormCustomers) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSormCustomersMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSormCustomers)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSormCustomers) Get() ([]models.SormCustomersData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormCustomersData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSormCustomersMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSormCustomers)(nil).Get))
}

// Update mocks base method.
func (m *MockSormCustomers) Update(arg0 models.SormCustomersData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSormCustomersMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSormCustomers)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockSormCustomers) Upsert(arg0 []models.SormCustomersData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSormCustomersMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSormCustomers)(nil).Upsert), arg0)
}
