// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: IssueTypes)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIssueTypes is a mock of IssueTypes interface.
type MockIssueTypes struct {
	ctrl     *gomock.Controller
	recorder *MockIssueTypesMockRecorder
}

// MockIssueTypesMockRecorder is the mock recorder for MockIssueTypes.
type MockIssueTypesMockRecorder struct {
	mock *MockIssueTypes
}

// NewMockIssueTypes creates a new mock instance.
func NewMockIssueTypes(ctrl *gomock.Controller) *MockIssueTypes {
	mock := &MockIssueTypes{ctrl: ctrl}
	mock.recorder = &MockIssueTypesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueTypes) EXPECT() *MockIssueTypesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIssueTypes) Create(arg0 models.IssueTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIssueTypesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueTypes)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIssueTypes) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIssueTypesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIssueTypes)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockIssueTypes) Get() ([]models.IssueTypeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.IssueTypeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueTypesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueTypes)(nil).Get))
}

// Update mocks base method.
func (m *MockIssueTypes) Update(arg0 models.IssueTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIssueTypesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueTypes)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockIssueTypes) Upsert(arg0 models.IssueTypeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIssueTypesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIssueTypes)(nil).Upsert), arg0)
}
