// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: RadiusAttributes)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRadiusAttributes is a mock of RadiusAttributes interface.
type MockRadiusAttributes struct {
	ctrl     *gomock.Controller
	recorder *MockRadiusAttributesMockRecorder
}

// MockRadiusAttributesMockRecorder is the mock recorder for MockRadiusAttributes.
type MockRadiusAttributesMockRecorder struct {
	mock *MockRadiusAttributes
}

// NewMockRadiusAttributes creates a new mock instance.
func NewMockRadiusAttributes(ctrl *gomock.Controller) *MockRadiusAttributes {
	mock := &MockRadiusAttributes{ctrl: ctrl}
	mock.recorder = &MockRadiusAttributesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadiusAttributes) EXPECT() *MockRadiusAttributesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRadiusAttributes) Create(arg0 models.RadiusAttributeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRadiusAttributesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRadiusAttributes)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockRadiusAttributes) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRadiusAttributesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRadiusAttributes)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockRadiusAttributes) Get() ([]models.RadiusAttributeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.RadiusAttributeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRadiusAttributesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRadiusAttributes)(nil).Get))
}

// Update mocks base method.
func (m *MockRadiusAttributes) Update(arg0 models.RadiusAttributeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRadiusAttributesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRadiusAttributes)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockRadiusAttributes) Upsert(arg0 models.RadiusAttributeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRadiusAttributesMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRadiusAttributes)(nil).Upsert), arg0)
}
