// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: SormGateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSormGateway is a mock of SormGateway interface.
type MockSormGateway struct {
	ctrl     *gomock.Controller
	recorder *MockSormGatewayMockRecorder
}

// MockSormGatewayMockRecorder is the mock recorder for MockSormGateway.
type MockSormGatewayMockRecorder struct {
	mock *MockSormGateway
}

// NewMockSormGateway creates a new mock instance.
func NewMockSormGateway(ctrl *gomock.Controller) *MockSormGateway {
	mock := &MockSormGateway{ctrl: ctrl}
	mock.recorder = &MockSormGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSormGateway) EXPECT() *MockSormGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSormGateway) Create(arg0 models.SormGatewayData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSormGatewayMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSormGateway)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockSormGateway) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSormGatewayMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSormGateway)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSormGateway) Get() ([]models.SormGatewayData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormGatewayData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSormGatewayMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSormGateway)(nil).Get))
}

// Update mocks base method.
func (m *MockSormGateway) Update(arg0 models.SormGatewayData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSormGatewayMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSormGateway)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockSormGateway) Upsert(arg0 models.SormGatewayData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSormGatewayMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSormGateway)(nil).Upsert), arg0)
}
