// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DeviceStates)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceStates is a mock of DeviceStates interface.
type MockDeviceStates struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStatesMockRecorder
}

// MockDeviceStatesMockRecorder is the mock recorder for MockDeviceStates.
type MockDeviceStatesMockRecorder struct {
	mock *MockDeviceStates
}

// NewMockDeviceStates creates a new mock instance.
func NewMockDeviceStates(ctrl *gomock.Controller) *MockDeviceStates {
	mock := &MockDeviceStates{ctrl: ctrl}
	mock.recorder = &MockDeviceStatesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceStates) EXPECT() *MockDeviceStatesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeviceStates) Create(arg0 models.DeviceStateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDeviceStatesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeviceStates)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDeviceStates) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeviceStatesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeviceStates)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockDeviceStates) Get() ([]models.DeviceStateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.DeviceStateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeviceStatesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeviceStates)(nil).Get))
}

// Update mocks base method.
func (m *MockDeviceStates) Update(arg0 models.DeviceStateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDeviceStatesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeviceStates)(nil).Update), arg0)
}
