// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: DhcpPools)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDhcpPools is a mock of DhcpPools interface.
type MockDhcpPools struct {
	ctrl     *gomock.Controller
	recorder *MockDhcpPoolsMockRecorder
}

// MockDhcpPoolsMockRecorder is the mock recorder for MockDhcpPools.
type MockDhcpPoolsMockRecorder struct {
	mock *MockDhcpPools
}

// NewMockDhcpPools creates a new mock instance.
func NewMockDhcpPools(ctrl *gomock.Controller) *MockDhcpPools {
	mock := &MockDhcpPools{ctrl: ctrl}
	mock.recorder = &MockDhcpPoolsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDhcpPools) EXPECT() *MockDhcpPoolsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDhcpPools) Create(arg0 []models.DhcpPoolData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDhcpPoolsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDhcpPools)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockDhcpPools) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDhcpPoolsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDhcpPools)(nil).Delete), arg0)
}

// DeleteAll mocks base method.
func (m *MockDhcpPools) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockDhcpPoolsMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockDhcpPools)(nil).DeleteAll))
}

// Get mocks base method.
func (m *MockDhcpPools) Get() ([]models.DhcpPoolData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.DhcpPoolData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDhcpPoolsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDhcpPools)(nil).Get))
}

// Update mocks base method.
func (m *MockDhcpPools) Update(arg0 models.DhcpPoolData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDhcpPoolsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDhcpPools)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockDhcpPools) Upsert(arg0 models.DhcpPoolData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockDhcpPoolsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockDhcpPools)(nil).Upsert), arg0)
}
