// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: MapNodes)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMapNodes is a mock of MapNodes interface.
type MockMapNodes struct {
	ctrl     *gomock.Controller
	recorder *MockMapNodesMockRecorder
}

// MockMapNodesMockRecorder is the mock recorder for MockMapNodes.
type MockMapNodesMockRecorder struct {
	mock *MockMapNodes
}

// NewMockMapNodes creates a new mock instance.
func NewMockMapNodes(ctrl *gomock.Controller) *MockMapNodes {
	mock := &MockMapNodes{ctrl: ctrl}
	mock.recorder = &MockMapNodesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapNodes) EXPECT() *MockMapNodesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMapNodes) Create(arg0 models.MapNodeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMapNodesMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMapNodes)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockMapNodes) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMapNodesMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMapNodes)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockMapNodes) Get() ([]models.MapNodeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.MapNodeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMapNodesMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMapNodes)(nil).Get))
}

// Update mocks base method.
func (m *MockMapNodes) Update(arg0 models.MapNodeData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMapNodesMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMapNodes)(nil).Update), arg0)
}
