// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: IpNumbering)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIpNumbering is a mock of IpNumbering interface.
type MockIpNumbering struct {
	ctrl     *gomock.Controller
	recorder *MockIpNumberingMockRecorder
}

// MockIpNumberingMockRecorder is the mock recorder for MockIpNumbering.
type MockIpNumberingMockRecorder struct {
	mock *MockIpNumbering
}

// NewMockIpNumbering creates a new mock instance.
func NewMockIpNumbering(ctrl *gomock.Controller) *MockIpNumbering {
	mock := &MockIpNumbering{ctrl: ctrl}
	mock.recorder = &MockIpNumberingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpNumbering) EXPECT() *MockIpNumberingMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIpNumbering) Create(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIpNumberingMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIpNumbering)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockIpNumbering) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIpNumberingMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIpNumbering)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockIpNumbering) Get() ([]models.SormIpNumberingData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.SormIpNumberingData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIpNumberingMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIpNumbering)(nil).Get))
}

// Update mocks base method.
func (m *MockIpNumbering) Update(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIpNumberingMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIpNumbering)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockIpNumbering) Upsert(arg0 models.SormIpNumberingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIpNumberingMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIpNumbering)(nil).Upsert), arg0)
}
