// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: PaymentSystems)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPaymentSystems is a mock of PaymentSystems interface.
type MockPaymentSystems struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentSystemsMockRecorder
}

// MockPaymentSystemsMockRecorder is the mock recorder for MockPaymentSystems.
type MockPaymentSystemsMockRecorder struct {
	mock *MockPaymentSystems
}

// NewMockPaymentSystems creates a new mock instance.
func NewMockPaymentSystems(ctrl *gomock.Controller) *MockPaymentSystems {
	mock := &MockPaymentSystems{ctrl: ctrl}
	mock.recorder = &MockPaymentSystemsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentSystems) EXPECT() *MockPaymentSystemsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentSystems) Create(arg0 models.PaymentSystemData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPaymentSystemsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentSystems)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockPaymentSystems) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPaymentSystemsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPaymentSystems)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockPaymentSystems) Get() ([]models.PaymentSystemData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.PaymentSystemData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentSystemsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentSystems)(nil).Get))
}

// Update mocks base method.
func (m *MockPaymentSystems) Update(arg0 models.PaymentSystemData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPaymentSystemsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentSystems)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockPaymentSystems) Upsert(arg0 models.PaymentSystemData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPaymentSystemsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPaymentSystems)(nil).Upsert), arg0)
}
