// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: RadiusVendors)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRadiusVendors is a mock of RadiusVendors interface.
type MockRadiusVendors struct {
	ctrl     *gomock.Controller
	recorder *MockRadiusVendorsMockRecorder
}

// MockRadiusVendorsMockRecorder is the mock recorder for MockRadiusVendors.
type MockRadiusVendorsMockRecorder struct {
	mock *MockRadiusVendors
}

// NewMockRadiusVendors creates a new mock instance.
func NewMockRadiusVendors(ctrl *gomock.Controller) *MockRadiusVendors {
	mock := &MockRadiusVendors{ctrl: ctrl}
	mock.recorder = &MockRadiusVendorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadiusVendors) EXPECT() *MockRadiusVendorsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRadiusVendors) Create(arg0 models.RadiusVendorData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRadiusVendorsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRadiusVendors)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockRadiusVendors) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRadiusVendorsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRadiusVendors)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockRadiusVendors) Get() ([]models.RadiusVendorData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.RadiusVendorData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRadiusVendorsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRadiusVendors)(nil).Get))
}

// Update mocks base method.
func (m *MockRadiusVendors) Update(arg0 models.RadiusVendorData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRadiusVendorsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRadiusVendors)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockRadiusVendors) Upsert(arg0 models.RadiusVendorData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRadiusVendorsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRadiusVendors)(nil).Upsert), arg0)
}
