// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/pkg/repository (interfaces: HardwareModels)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "code.evixo.ru/ncc/ncc-backend/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockHardwareModels is a mock of HardwareModels interface.
type MockHardwareModels struct {
	ctrl     *gomock.Controller
	recorder *MockHardwareModelsMockRecorder
}

// MockHardwareModelsMockRecorder is the mock recorder for MockHardwareModels.
type MockHardwareModelsMockRecorder struct {
	mock *MockHardwareModels
}

// NewMockHardwareModels creates a new mock instance.
func NewMockHardwareModels(ctrl *gomock.Controller) *MockHardwareModels {
	mock := &MockHardwareModels{ctrl: ctrl}
	mock.recorder = &MockHardwareModelsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHardwareModels) EXPECT() *MockHardwareModelsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHardwareModels) Create(arg0 models.HardwareModelData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHardwareModelsMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHardwareModels)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockHardwareModels) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHardwareModelsMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHardwareModels)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockHardwareModels) Get() ([]models.HardwareModelData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]models.HardwareModelData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHardwareModelsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHardwareModels)(nil).Get))
}

// Update mocks base method.
func (m *MockHardwareModels) Update(arg0 models.HardwareModelData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHardwareModelsMockRecorder) Update(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHardwareModels)(nil).Update), arg0)
}

// Upsert mocks base method.
func (m *MockHardwareModels) Upsert(arg0 models.HardwareModelData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockHardwareModelsMockRecorder) Upsert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockHardwareModels)(nil).Upsert), arg0)
}
