apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-payment-gateway
  name: ncc-payment-gateway
  namespace: $NAMESPACE
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-payment-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-payment-gateway
    spec:
      affinity: { }
      containers:
        - env:
            - name: LISTEN
              valueFrom:
                configMapKeyRef:
                  key: LISTEN
                  name: ncc-payment-gateway-config
                  optional: false
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  key: API_URL
                  name: ncc-payment-gateway-config
                  optional: false
            - name: API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: API_TOKEN
                  name: ncc-payment-gateway-config
                  optional: false
            - name: TZ
              value: Europe/Moscow
          image: registry.evixo.ru/dev/ncc-backend:$RELEASE
          imagePullPolicy: Always
          name: ncc-payment-gateway
          command:
            - ./bin
          workingDir: /app
          args:
            - payment-gateway
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
