apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-exporter
  name: ncc-scheduler-exporter
  namespace: $NAMESPACE
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-exporter
    spec:
      affinity: {}
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: ncc-db-config
                  optional: false
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: ncc-db-config
                  optional: false
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: ncc-db-config
                  optional: false
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: ncc-db-config
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: ncc-db-config
                  optional: false
            - name: EXPORTER_HOST
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_HOST
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_BADSHOST
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_BADSHOST
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_KEY
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_KEY
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_PATH
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_PATH
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_USERNAME
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_BADSUSERNAME
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_BADSUSERNAME
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_PASSWORD
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_BADSPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_BADSPASSWORD
                  name: ncc-exporter-config
                  optional: false
            - name: EXPORTER_TYPE
              valueFrom:
                configMapKeyRef:
                  key: EXPORTER_TYPE
                  name: ncc-exporter-config
                  optional: false
            - name: TZ
              value: Europe/Moscow
          image: registry.evixo.ru/dev/ncc-backend:$RELEASE
          imagePullPolicy: Always
          name: ncc-scheduler-exporter
          command:
            - ./bin
          workingDir: /app
          args:
              - scheduler
              - --exporter
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30