apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-informings
  name: ncc-scheduler-informings
  namespace: $NAMESPACE
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-informings
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-$NAMESPACE-ncc-scheduler-informings
    spec:
      affinity: {}
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: ncc-db-config
                  optional: false
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: ncc-db-config
                  optional: false
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: ncc-db-config
                  optional: false
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: ncc-db-config
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: ncc-db-config
                  optional: false
            - name: INFORMINGS_SMSPROVIDER_URI
              valueFrom:
                configMapKeyRef:
                  key: INFORMINGS_SMSPROVIDER_URI
                  name: ncc-informings-config
                  optional: false
            - name: INFORMINGS_SMSPROVIDER_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: INFORMINGS_SMSPROVIDER_TOKEN
                  name: ncc-informings-config
                  optional: false
            - name: TZ
              value: Europe/Moscow
          image: registry.evixo.ru/dev/ncc-backend:$RELEASE
          imagePullPolicy: Always
          name: ncc-scheduler-informings
          command:
            - ./bin
          workingDir: /app
          args:
              - scheduler
              - --informings
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30