// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/services/simulator/interfaces (interfaces: RadiusKillSessionsUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "code.evixo.ru/ncc/ncc-backend/services/simulator/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRadiusKillSessionsUsecase is a mock of RadiusKillSessionsUsecase interface.
type MockRadiusKillSessionsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRadiusKillSessionsUsecaseMockRecorder
}

// MockRadiusKillSessionsUsecaseMockRecorder is the mock recorder for MockRadiusKillSessionsUsecase.
type MockRadiusKillSessionsUsecaseMockRecorder struct {
	mock *MockRadiusKillSessionsUsecase
}

// NewMockRadiusKillSessionsUsecase creates a new mock instance.
func NewMockRadiusKillSessionsUsecase(ctrl *gomock.Controller) *MockRadiusKillSessionsUsecase {
	mock := &MockRadiusKillSessionsUsecase{ctrl: ctrl}
	mock.recorder = &MockRadiusKillSessionsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadiusKillSessionsUsecase) EXPECT() *MockRadiusKillSessionsUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRadiusKillSessionsUsecase) Execute(arg0 dto.RadiusKillSessionsUsecaseRequest) (dto.RadiusKillSessionsUsecaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(dto.RadiusKillSessionsUsecaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRadiusKillSessionsUsecaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRadiusKillSessionsUsecase)(nil).Execute), arg0)
}
