// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/services/simulator/interfaces (interfaces: FakeDataCreateUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "code.evixo.ru/ncc/ncc-backend/services/simulator/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockFakeDataCreateUsecase is a mock of FakeDataCreateUsecase interface.
type MockFakeDataCreateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFakeDataCreateUsecaseMockRecorder
}

// MockFakeDataCreateUsecaseMockRecorder is the mock recorder for MockFakeDataCreateUsecase.
type MockFakeDataCreateUsecaseMockRecorder struct {
	mock *MockFakeDataCreateUsecase
}

// NewMockFakeDataCreateUsecase creates a new mock instance.
func NewMockFakeDataCreateUsecase(ctrl *gomock.Controller) *MockFakeDataCreateUsecase {
	mock := &MockFakeDataCreateUsecase{ctrl: ctrl}
	mock.recorder = &MockFakeDataCreateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFakeDataCreateUsecase) EXPECT() *MockFakeDataCreateUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFakeDataCreateUsecase) Execute(arg0 dto.FakeDataCreateUsecaseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockFakeDataCreateUsecaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFakeDataCreateUsecase)(nil).Execute), arg0)
}
