// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/services/simulator/interfaces (interfaces: RadiusStopAllUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "code.evixo.ru/ncc/ncc-backend/services/simulator/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRadiusStopAllUsecase is a mock of RadiusStopAllUsecase interface.
type MockRadiusStopAllUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRadiusStopAllUsecaseMockRecorder
}

// MockRadiusStopAllUsecaseMockRecorder is the mock recorder for MockRadiusStopAllUsecase.
type MockRadiusStopAllUsecaseMockRecorder struct {
	mock *MockRadiusStopAllUsecase
}

// NewMockRadiusStopAllUsecase creates a new mock instance.
func NewMockRadiusStopAllUsecase(ctrl *gomock.Controller) *MockRadiusStopAllUsecase {
	mock := &MockRadiusStopAllUsecase{ctrl: ctrl}
	mock.recorder = &MockRadiusStopAllUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRadiusStopAllUsecase) EXPECT() *MockRadiusStopAllUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRadiusStopAllUsecase) Execute(arg0 dto.RadiusUsecaseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRadiusStopAllUsecaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRadiusStopAllUsecase)(nil).Execute), arg0)
}
