// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/services/simulator/interfaces (interfaces: BrasSetParamsUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "code.evixo.ru/ncc/ncc-backend/services/simulator/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockBrasSetParamsUsecase is a mock of BrasSetParamsUsecase interface.
type MockBrasSetParamsUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBrasSetParamsUsecaseMockRecorder
}

// MockBrasSetParamsUsecaseMockRecorder is the mock recorder for MockBrasSetParamsUsecase.
type MockBrasSetParamsUsecaseMockRecorder struct {
	mock *MockBrasSetParamsUsecase
}

// NewMockBrasSetParamsUsecase creates a new mock instance.
func NewMockBrasSetParamsUsecase(ctrl *gomock.Controller) *MockBrasSetParamsUsecase {
	mock := &MockBrasSetParamsUsecase{ctrl: ctrl}
	mock.recorder = &MockBrasSetParamsUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrasSetParamsUsecase) EXPECT() *MockBrasSetParamsUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBrasSetParamsUsecase) Execute(arg0 dto.BrasSetParamsUsecaseRequest) (dto.BrasSetParamsUsecaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(dto.BrasSetParamsUsecaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBrasSetParamsUsecaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBrasSetParamsUsecase)(nil).Execute), arg0)
}
