// Code generated by MockGen. DO NOT EDIT.
// Source: code.evixo.ru/ncc/ncc-backend/services/simulator/interfaces (interfaces: FakeDataClearUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "code.evixo.ru/ncc/ncc-backend/services/simulator/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockFakeDataClearUsecase is a mock of FakeDataClearUsecase interface.
type MockFakeDataClearUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFakeDataClearUsecaseMockRecorder
}

// MockFakeDataClearUsecaseMockRecorder is the mock recorder for MockFakeDataClearUsecase.
type MockFakeDataClearUsecaseMockRecorder struct {
	mock *MockFakeDataClearUsecase
}

// NewMockFakeDataClearUsecase creates a new mock instance.
func NewMockFakeDataClearUsecase(ctrl *gomock.Controller) *MockFakeDataClearUsecase {
	mock := &MockFakeDataClearUsecase{ctrl: ctrl}
	mock.recorder = &MockFakeDataClearUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFakeDataClearUsecase) EXPECT() *MockFakeDataClearUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFakeDataClearUsecase) Execute(arg0 dto.FakeDataClearUsecaseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockFakeDataClearUsecaseMockRecorder) Execute(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFakeDataClearUsecase)(nil).Execute), arg0)
}
