// Code generated by "stringer -type=PacketCode"; DO NOT EDIT.

package radius

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessRequest-1]
	_ = x[AccessAccept-2]
	_ = x[AccessReject-3]
	_ = x[AccountingRequest-4]
	_ = x[AccountingResponse-5]
	_ = x[AccessChallenge-11]
	_ = x[StatusServer-12]
	_ = x[StatusClient-13]
	_ = x[Reserved-255]
}

const (
	_PacketCode_name_0 = "AccessRequestAccessAcceptAccessRejectAccountingRequestAccountingResponse"
	_PacketCode_name_1 = "AccessChallengeStatusServerStatusClient"
	_PacketCode_name_2 = "Reserved"
)

var (
	_PacketCode_index_0 = [...]uint8{0, 13, 25, 37, 54, 72}
	_PacketCode_index_1 = [...]uint8{0, 15, 27, 39}
)

func (i PacketCode) String() string {
	switch {
	case 1 <= i && i <= 5:
		i -= 1
		return _PacketCode_name_0[_PacketCode_index_0[i]:_PacketCode_index_0[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _PacketCode_name_1[_PacketCode_index_1[i]:_PacketCode_index_1[i+1]]
	case i == 255:
		return _PacketCode_name_2
	default:
		return "PacketCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
